const MESO = new Map()


MESO.set('CANINDÉ','NORTE CEARENSE');
MESO.set('BATURITÉ','NORTE CEARENSE');
MESO.set('SERTÃO DE INHAMUNS','SERTÕES CEARENSES');
MESO.set('SERTÃO DE SENADOR POMPEU','SERTÕES CEARENSES');
MESO.set('CARIRI','SUL CEARENSE');
MESO.set('ITAPIPOCA','NORTE CEARENSE');
MESO.set('CHOROZINHO','NORTE CEARENSE');
MESO.set('BREJO SANTO','SUL CEARENSE');
MESO.set('MÉDIO JAGUARIBE','JAGUARIBE');
MESO.set('IGUATU','CENTRO-SUL CEARENSE');
MESO.set('COREAÚ','NOROESTE CEARENSE');
MESO.set('SOBRAL','NOROESTE CEARENSE');
MESO.set('IPU','NOROESTE CEARENSE');
MESO.set('BAIXO CURU','NORTE CEARENSE');
MESO.set('URUBURETAMA','NORTE CEARENSE');
MESO.set('BAIXO JAGUARIBE','JAGUARIBE');
MESO.set('VÁRZEA ALEGRE','CENTRO-SUL CEARENSE');
MESO.set('PACAJUS','METROPOLITANA DE FORTALEZA');
MESO.set('MERUOCA','NOROESTE CEARENSE');
MESO.set('CASCAVEL','NORTE CEARENSE');
MESO.set('SERTÃO DE QUIXERAMOBIM','SERTÕES CEARENSES');
MESO.set('SERRA DO PEREIRO','JAGUARIBE');
MESO.set('CARIRIAÇU','SUL CEARENSE');
MESO.set('SANTA QUITÉRIA','NOROESTE CEARENSE');
MESO.set('BARRO','SUL CEARENSE');
MESO.set('SERTÃO DE CRATEÚS','SERTÕES CEARENSES');
MESO.set('FORTALEZA','METROPOLITANA DE FORTALEZA');
MESO.set('LITORAL DE CAMOCIM E ACARAÚ','NOROESTE CEARENSE');
MESO.set('LITORAL DE ARACATI','JAGUARIBE');
MESO.set('CHAPADA DO ARARIPE','SUL CEARENSE');
MESO.set('IBIAPABA','NOROESTE CEARENSE');
MESO.set('MÉDIO CURU','NORTE CEARENSE');
MESO.set('LAVRAS DA MANGABEIRA','CENTRO-SUL CEARENSE');


export {MESO}